default_context:
  project_name: 'Smoothify Server'
  project_slug: 'smoothify-server'
  domain_main: 'api.smoothify.tasercake.com'
  domain_staging: 'next.api.smoothify.tasercake.com'
  docker_swarm_stack_name_main: 'smoothify-api'
  docker_swarm_stack_name_staging: 'next-smoothify-api'
  secret_key: '5aed2f1f090a2e6994e33ddafb7d733bc0f4766b15f69dbd1a6c324406ed'
  first_superuser: 'admin@api.smoothify.tasercake.com'
  first_superuser_password: 'Gulabjam98998898Tasercake42'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.api.smoothify.tasercake.com", "https://next.api.smoothify.tasercake.com", "https://api.smoothify.tasercake.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@api.smoothify.tasercake.com'
  postgres_password: 'Gulabjam98'
  pgadmin_default_user: 'admin@smoothify.com'
  pgadmin_default_user_password: 'Gulabjam98998898Tasercake42'
  traefik_constraint_tag: 'api.smoothify.tasercake.com'
  traefik_constraint_tag_staging: 'next.api.smoothify.tasercake.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Gulabjam98998898Tasercake42'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
