[package]
name = "loob-core"
edition.workspace = true
version.workspace = true

[dependencies]
loob-optim = { workspace = true }
loob-yt = { workspace = true }
anyhow = { workspace = true }
ndarray = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
