[package]
name = "loob-core"
edition.workspace = true
version.workspace = true

[dependencies]
loob-optim = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
fs2 = { workspace = true }
atomicwrites = { workspace = true }
rustfft = { workspace = true }
sha2 = { workspace = true }
symphonia = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
