[package]
name = "loob-core"
version.workspace = true
edition.workspace = true

[dependencies]
loob-optim = { workspace = true }
loob-yt = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
ndarray = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
